import asyncio
import io
import json
import os
import time
import urllib3
from typing import Annotated, ClassVar, Literal, Optional, Sequence, TypedDict

from dotenv import load_dotenv

from langchain.agents import AgentType, initialize_agent
from langchain.prompts.chat import ChatPromptTemplate, MessagesPlaceholder
from langchain_community.tools import DuckDuckGoSearchRun, WikipediaQueryRun
from langchain_community.utilities import WikipediaAPIWrapper
from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage
from langchain_core.tools import Tool
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_mcp_adapters.client import MultiServerMCPClient
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode, tools_condition
from pydantic import BaseModel, Field

load_dotenv()

llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",
    temperature=0.3
)

class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], add_messages]
    result: str 
    requires_agent: bool = False
    planned : Literal["1", "2", "3"]



class DecisionOutput(BaseModel):
    """Output object of the student-assisting agent."""
    requires_agent: bool = Field(description="Determine whether the query can be answered directly or requires action (research, Q&A, educational counselor, etc.).")
    answer: Optional[str] = Field(default=None, description="The response should be None if the user query requires research, Q&A, or creating a program; otherwise, provide a direct answer.")



class PlanningAgent(BaseModel):
    planned: Literal["1", "2", "3"] = Field(default="1")



class QaDecisionOutput(BaseModel):
    requires_answer: bool = Field(description="Determine whether the user has question.")


class QaOutput(BaseModel):
    questions : list[str] = Field(description="Questions generated by AI.")
    options : list[str] = Field(description="Options of questions")
    answers: list[str] = Field(default=None,description="Answers of questions")


decision_making_prompt = """
Based on the user query, decide if you need to perform a research, Q&A, or educational help (etc.) or if you can answer the question directly.
- You should answer the question directly only for simple conversational questions, like "how are you?".
"""

### MCP:
client = MultiServerMCPClient(
    {
       
        "time": {
            "command": "uvx",
            "args": [
                "mcp-server-time",
                "--local-timezone=America/New_York"
            ],
            "transport": "stdio",
        }
    }
)

async def run_graph():

#### Decission Node:
  
    def decision_node(state: AgentState):
        decision_llm = llm.with_structured_output(DecisionOutput)

        system_prompt = SystemMessage(content=decision_making_prompt)

        response : DecisionOutput = decision_llm.invoke([system_prompt, *state["messages"]])
        
        if response.answer:
            return {"result": response.answer, "requires_agent": False}
        else:
            return {"requires_agent": response.requires_agent}

    ### Router for decision:

    def decision_router(state: AgentState):
        if state["requires_agent"]:
            return "planning"
        else:
            return "end"


#### Planning Node:


    planning_prompt = """
            Categorize the following user query into one of these categories:
            Categories:
            1 : Research Mode, when the user asks you to do research.
            2 : Example Question, when the user asks for example questions
            3 : Educational Counselorn Mode, when the user asks you to educational help.

            Examples:
            1. User query: 'What is deep learning?' -> 1
            2. User query: 'I need some practice questions for a biology exam. Can you give me a few example questions related to photosynthesis and cellular respiration?' -> 2
            3. User query: 'I am a beginner at learning English. How can I improve my English?' -> 3"""



    def planning_node(state: AgentState):
        
        system_prompt = SystemMessage(content=planning_prompt)

        planning_llm = llm.with_structured_output(PlanningAgent)

        response : PlanningAgent = planning_llm.invoke([system_prompt,  *state["messages"]])

        return {"planned": response.planned}


    ### Router for planning:


    def planning_router(state: AgentState):
        if state["planned"] == "1":
            return "searching_node"
        elif state["planned"] == "2":
            return "qa_node"
        elif state["planned"] == "3":
            return "mentor_node"


#### Research Node:
    ### TOOLS:
    time_tool = await client.get_tools()
    
    wiki_api = WikipediaAPIWrapper(lang="en", top_k_results=4, doc_content_chars_max=1000)
    wikipedia_tool = Tool(
        name="wikipedia",
        func=WikipediaQueryRun(api_wrapper=wiki_api).run,
        description="Look up factual and academic info."
    )
    duckduckgo_tool = Tool(
        name="duckduckgo_search",
        func=DuckDuckGoSearchRun().run,
        description="Search the web for current info."
    )
    custom_tools = [duckduckgo_tool, wikipedia_tool]

    all_tools = time_tool + custom_tools

    def searching_node(state:AgentState):
        query =  state["messages"]
        system_prompt_template = ChatPromptTemplate.from_messages([
            SystemMessage(content="You are a dedicated research assistant, highly skilled in information synthesis and critical analysis."),
            MessagesPlaceholder(variable_name="messages"), 
        ])

        prompt_to_invoke = system_prompt_template.format_prompt(messages=query)

        response = llm.bind_tools(all_tools).invoke(prompt_to_invoke)

        return {"messages": response, "result": response.content}

#### QA Node:

    qa_prompt = """You are a question-generating assistant. 
    Your sole purpose is to create questions with options(A, B, C, D ,E) based on the user's request. 
    Your questions should be relevant, thought-provoking, and tailored to the specific topic provided. 
    You can ask follow-up questions to better understand the user's needs before generating the questions.
    If question number is not specify in the user query, you should generate 5 questions.
    If question number is specify in the user query, you should generate that number of questions.
    """

    def qa_node(state: AgentState):
        system_prompt = SystemMessage(content=qa_prompt)

        qa_llm = llm.with_structured_output(QaOutput)

        response : QaOutput = qa_llm.invoke([system_prompt,  *state["messages"]])

        result= ""
        for i in range(len(response.questions)):
            result += f"Question {i+1}: {response.questions[i]}\nOptions: {response.options[i]}\n\n"

        return {"result": result}

#### Mentor Node:

    mentor_prompt="""You are an expert academic advisor, mentoring students and strategic learning planner. 
    Your primary function is to create highly effective, personalized, and realistic study schedules for students. 
    Your goal is to help users manage their time efficiently, reduce exam-related stress, and optimize their learning for long-term retention, not just last-minute cramming."""



    def mentor_node(state: AgentState):
        system_prompt = SystemMessage(content=mentor_prompt)

        response = llm.invoke([system_prompt,  *state["messages"]])

        return {"result": response.content}


#### Graph:

    workflow = StateGraph(AgentState)

    workflow.add_node("decision_node", decision_node)
    workflow.add_node("tools", ToolNode(all_tools))
    workflow.add_node("planning_node", planning_node)
    workflow.add_node("searching_node", searching_node)
    workflow.add_node("qa_node", qa_node)
    workflow.add_node("mentor_node", mentor_node)

    workflow.add_edge(START, "decision_node")

    workflow.add_conditional_edges(
        "decision_node",
        decision_router,
        {"end": END, "planning": "planning_node"}
    )
    
    workflow.add_conditional_edges(
        "planning_node",
        planning_router,
        {"searching_node": "searching_node", "qa_node": "qa_node", "mentor_node": "mentor_node"}
    )
    workflow.add_edge("searching_node", END)
    workflow.add_conditional_edges(
        "searching_node",
        tools_condition,
    )
    workflow.add_edge("tools", "searching_node")
    workflow.add_edge("qa_node", END)
    workflow.add_edge("mentor_node", END)

    #memory = MemorySaver()
    return workflow.compile()


graph = asyncio.run(run_graph())
